# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3HaEs1dFexm4Fo9srSTV5bFGVp2sjQb
"""

import requests

def fetch_covid_data():
    url = "https://data.covid19india.org/v4/min/timeseries.min.json"
    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        return data
    except requests.exceptions.RequestException as e:
        print("Error fetching data:", e)

if __name__ == "__main__":
    covid_data = fetch_covid_data()
    if covid_data:
        print(covid_data)